name: Bug report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: What did you observe?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Minimal, deterministic steps.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: OS, pwsh version, toolchain.
    validations:
      required: true
