name: Feature request
description: Propose an enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Problem statement
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
    validations:
      required: false
